"""adjusts models

Revision ID: 6dbc394b6164
Revises: f0620043cdfd
Create Date: 2023-11-30 13:51:59.529972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dbc394b6164'
down_revision = 'f0620043cdfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_account_id_products', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_orders_account_id_accounts'), 'accounts', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_orders_account_id_accounts'), type_='foreignkey')
        batch_op.create_foreign_key('fk_orders_account_id_products', 'products', ['account_id'], ['id'])

    # ### end Alembic commands ###
