"""empty message

Revision ID: 829ee5482e16
Revises: f3ef6e468cae
Create Date: 2023-12-01 01:52:56.991124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829ee5482e16'
down_revision = 'f3ef6e468cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_product_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_product_associations_order_id_orders')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_order_product_associations_product_id_products')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('order_product_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_product_association',
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='fk_order_product_association_order_id_orders'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_order_product_association_product_id_products')
    )
    op.drop_table('order_product_associations')
    # ### end Alembic commands ###
